my_portfolio/urls.py
from django.contrib import admin

from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

import notifications.urls

from article.views import article_list
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # home
    path('', article_list, name='home'),
    # reset password app
    # path('password-reset/', include('password_reset.urls')),
    url(r'^password-reset/$', auth_views.PasswordResetView.as_view(
             template_name="passwordreset/password_reset_form.html",
             email_template_name="passwordreset/password_reset_email.html",
             subject_template_name="passwordreset/password_reset_subject.txt",
             success_url="/password-reset-done/"),
        name="password_reset"),
    url(r'^password-reset-done/$', auth_views.PasswordResetDoneView.as_view(template_name="passwordreset/password_reset_done.html"),
         name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.PasswordResetConfirmView.as_view(template_name="passwordreset/password_reset_confirm.html"),

         name="password_reset_confirm"),
    url(r'^password-reset-complete/$', auth_views.PasswordResetCompleteView.as_view(template_name="passwordreset/password_reset_complete.html"),
        name="password_reset_complete"),
    # set app's url
    path('article/', include('article.urls', namespace='article')),
    # userprofile
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    # comment
    path('comment/', include('comment.urls', namespace='comment')),
    # djang-notifications
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # notice
    path('notice/', include('notice.urls', namespace='notice')),
    # # django-allauth
    path('accounts/', include('allauth.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [

    path('login/', views.user_login, name='login'),

    path('logout/', views.user_logout, name='logout'),

    path('register/', views.user_register, name='register'),

    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    phone = models.CharField(max_length=20, blank=True)

    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)

    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)

userprofile/forms.py
from django import forms

from django.contrib.auth.models import User

from .models import Profile


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()



class UserRegisterForm(forms.ModelForm):

    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError("input password again!")


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', 'avatar', 'bio')

userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .forms import UserLoginForm, UserRegisterForm

from .forms import ProfileForm
from .models import Profile

def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():

            data = user_login_form.cleaned_data
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                login(request, user)
                return redirect("article:article_list")
            else:
                return HttpResponse("username or password error,input again!")
        else:
            return HttpResponse("username or password invalid")
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = { 'form': user_login_form }
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse("GET/POST request only")

def user_logout(request):
    logout(request)
    return redirect("article:article_list")

def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            user_name=request.POST.get('username',None)
            password=request.POST.get('password',None)
            user = authenticate(username=user_name, password=password)
            if user:
                 login(request, user)
            return redirect("article:article_list")
        else:
            return HttpResponse("register context error,input again!")
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = { 'form': user_register_form }
        return render(request, 'userprofile/register.html', context)
    else:
        return HttpResponse("GET/POST request only")

@login_required(login_url='/userprofile/login/')
def user_delete(request, id):
    if request.method == 'POST':
        user = User.objects.get(id=id)
        if request.user == user:
            logout(request)
            user.delete()
            return redirect("article:article_list")
        else:
            return HttpResponse("you can't delete!")
    else:
        return HttpResponse("Post request only")

@login_required(login_url='/userprofile/login/')
def profile_edit(request, id):
    user = User.objects.get(id=id)
    if Profile.objects.filter(user_id=id).exists():
        profile = Profile.objects.get(user_id=id)
    else:
        profile = Profile.objects.create(user=user)


    if request.method == 'POST':
        if request.user != user:
            return HttpResponse("you can't delete!")

        profile_form = ProfileForm(request.POST, request.FILES)

        if profile_form.is_valid():
            profile_cd = profile_form.cleaned_data

            profile.phone = profile_cd['phone']
            profile.bio = profile_cd['bio']

            if 'avatar' in request.FILES:
                profile.avatar = profile_cd["avatar"]

            profile.save()
            return redirect("userprofile:edit", id=id)
        else:
            return HttpResponse("context error,input again!")

    elif request.method == 'GET':
        profile_form = ProfileForm()
        context = { 'profile_form': profile_form, 'profile': profile, 'user': user }
        return render(request, 'userprofile/edit.html', context)
    else:
        return HttpResponse("GET/POST request only")

templates/userprofile/edit.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} User information {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <div class="col-md-4">Username: {{ user.username }}</div>
            <br>
            {% if profile.avatar %}
                <div class="col-md-4">Photo</div>
                <img src="{{ profile.avatar.url }}" style="max-width: 20%; border-radius: 15%;" class="col-md-4">
            {% else %}
                <h5 class="col-md-4">Non Photo</h5>
            {% endif %}
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                <!-- avatar -->
                <div class="form-group col-md-4">
                    <label for="avatar">upload photo</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>

                <!-- phone -->
                <div class="form-group col-md-4">
                    <label for="phone">telephone</label>
                    <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                </div>
                <!-- bio -->
                <div class="form-group col-md-4">
                    <label for="bio">introduction</label>
                    <!-- text -->
                    <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                </div>
                <!-- submit -->
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/login.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} login {% endblock title %}
{% block content %}

    <div class="container">
        <div style="text-align: center" class="container-fluid mt-4">
            <h4 class="alert alert-info">login</h4>
        </div>





            <div class="row justify-content-center" >
                <form method="post" action="." style="min-width: 400px">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username">username</label>
                        <input type="text" class="form-control" id="username" name="username">
                        <small class="form-text text-muted ml-1">
                            <a href="{% url "userprofile:register" %}" style="color: cornflowerblue; ">
                                register
                            </a>
                        </small>


                    </div>
                    <!-- password -->
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" id="password" name="password">
                        <small class="form-text text-muted ml-1">
                            <a class="secondaryAction layui-text" href="{% url "password_reset" %}">
                                forget password?
                            </a>
                        </small>
                    </div>
                    <!-- submit -->
                    <button type="submit" class="btn btn-primary">YES</button>
                </form>
            </div>

    </div>
{% endblock content %}

templates/userprofile/register.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} login {% endblock title %}
{% block content %}

    <div class="container">
     <div style="text-align: center" class="container-fluid mt-4">
            <h4 class="alert alert-info">register</h4>
        </div>
    <div class="row justify-content-center">
        <form class="signup" id="signup_form" method="post" action="." style="min-width: 400px">
              {% csrf_token %}
                   <div class="form-group">
                <label for="id_username">username:</label>
                <div class="layui-input-inline">
                    <input type="text" name="username" placeholder="input username" autofocus="autofocus" minlength="1" maxlength="150" required="" id="id_username" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label for="id_email" class="layui-form-label">E-mail:</label>
                <input type="email" name="email" placeholder="input email address" id="id_email" class="form-control" required="">
            </div>
            <div class="form-group">
                <label for="id_password1" class="layui-form-label">Password:</label>
                <input type="password" name="password" placeholder="8 or more letters/numbers" required="" id="id_password1" class="form-control">
            </div>
            <div class="form-group">
                <label for="id_password2" class="layui-form-label">retype password</label>

                <input type="password" name="password2" placeholder="retype password" required="" id="id_password2" class="form-control">
            </div>
           <button type="submit" class="btn btn-primary">submit</button>
            <small class="form-text text-muted">
                if you have register, you can click here<a href="{% url 'userprofile:login' %}">login</a>。
            </small>
        </form>
    </div>

</div>
{% endblock content %}