article/urls.py
from django.urls import path

from . import views

app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    path('increase-likes/<int:id>/', views.IncreaseLikesView.as_view(), name='increase_likes'),

    path('list-view/', views.ArticleListView.as_view(), name='list_view'),
    path('detail-view/<int:pk>/', views.ArticleDetailView.as_view(), name='detail_view'),
    path('create-view/', views.ArticleCreateView.as_view(), name='create_view'),
]

my_portfolio/urls.py
from django.contrib import admin

from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

import notifications.urls

from article.views import article_list
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # home
    path('', article_list, name='home'),
    # reset password app
    # path('password-reset/', include('password_reset.urls')),
    url(r'^password-reset/$', auth_views.PasswordResetView.as_view(
             template_name="passwordreset/password_reset_form.html",
             email_template_name="passwordreset/password_reset_email.html",
             subject_template_name="passwordreset/password_reset_subject.txt",
             success_url="/password-reset-done/"),
        name="password_reset"),
    url(r'^password-reset-done/$', auth_views.PasswordResetDoneView.as_view(template_name="passwordreset/password_reset_done.html"),
         name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.PasswordResetConfirmView.as_view(template_name="passwordreset/password_reset_confirm.html"),

         name="password_reset_confirm"),
    url(r'^password-reset-complete/$', auth_views.PasswordResetCompleteView.as_view(template_name="passwordreset/password_reset_complete.html"),
        name="password_reset_complete"),
    # set app's url
    path('article/', include('article.urls', namespace='article')),
    # userprofile
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    # comment
    path('comment/', include('comment.urls', namespace='comment')),
    # djang-notifications
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # notice
    path('notice/', include('notice.urls', namespace='notice')),
    # # django-allauth
    path('accounts/', include('allauth.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [

    path('login/', views.user_login, name='login'),

    path('logout/', views.user_logout, name='logout'),

    path('register/', views.user_register, name='register'),

    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/back_to_top_func.html
<!-- https://ezbox.idv.tw/131/back-to-top-button-without-images -->
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="stylesheet" 
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" 
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" 
      crossorigin="anonymous"
    >
</head>

<body>

    {% include 'header.html' %}
    <div id="wrapper">
        {% block content %}{% endblock content %}
        <div id="push"></div>
    </div>
    {% include 'footer.html' %}

    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>

    {% block script %}{% endblock script %}

    {% include 'back_to_top_func.html' %}


    <style>
        html, body {
            height: 100%;
            margin: 0;
        }

        #wrapper {
            min-height: 100%;
            margin-bottom: -40px;
        }

        #footer,
        #push {
            height: 60px;
        }
    </style>

</body>

</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Copyright &copy; YangS67@cardiff.ac.uk 2023</h5>
    </div>
</footer>

templates/header.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'article:article_list' %}">My digital portfolio</a>
        <div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">Article</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% if unread_count %}
                                <svg viewBox="0 0 8 8"
                                     width="8px"
                                     height="8px">
                                    <circle cx="4"
                                            cy="4"
                                            r="4"
                                            fill="#ff6b6b"
                                    ></circle>
                                </svg>
                            {% endif %}
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url "notice:list" %}">Notice
                                {% if unread_count %}
                                    <span class="badge badge-danger">{{ unread_count }}</span>
                                {% endif %}
                            </a>
                            <a class="dropdown-item" href="{% url 'article:article_create' %}">Write Article</a>
                            <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>Information</a>
                            <a class="dropdown-item" href="#" onclick="user_delete()">delete user</a>
                            <a class="dropdown-item" href='{% url "userprofile:logout" %}'>logout</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userprofile:login' %}">login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% if user.is_authenticated %}
<form 
    style="display:none;" 
    id="user_delete"
    action="{% url 'userprofile:delete' user.id %}" 
    method="POST"
>
{% csrf_token %}
    <button type="submit">send</button>
</form>
    <script>
        function user_delete() {
            layer.open({
                title: "Delete?",
                content: "Delete user context?",
                yes: function(index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endif %}