article/urls.py
from django.urls import path

from . import views

app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    path('increase-likes/<int:id>/', views.IncreaseLikesView.as_view(), name='increase_likes'),

    path('list-view/', views.ArticleListView.as_view(), name='list_view'),
    path('detail-view/<int:pk>/', views.ArticleDetailView.as_view(), name='detail_view'),
    path('create-view/', views.ArticleCreateView.as_view(), name='create_view'),
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    path('post-comment/<int:article_id>', views.post_comment, name='post_comment'),
    path('post-comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply')
]

my_portfolio/urls.py
from django.contrib import admin

from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

import notifications.urls

from article.views import article_list
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # home
    path('', article_list, name='home'),
    # reset password app
    # path('password-reset/', include('password_reset.urls')),
    url(r'^password-reset/$', auth_views.PasswordResetView.as_view(
             template_name="passwordreset/password_reset_form.html",
             email_template_name="passwordreset/password_reset_email.html",
             subject_template_name="passwordreset/password_reset_subject.txt",
             success_url="/password-reset-done/"),
        name="password_reset"),
    url(r'^password-reset-done/$', auth_views.PasswordResetDoneView.as_view(template_name="passwordreset/password_reset_done.html"),
         name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.PasswordResetConfirmView.as_view(template_name="passwordreset/password_reset_confirm.html"),

         name="password_reset_confirm"),
    url(r'^password-reset-complete/$', auth_views.PasswordResetCompleteView.as_view(template_name="passwordreset/password_reset_complete.html"),
        name="password_reset_complete"),
    # set app's url
    path('article/', include('article.urls', namespace='article')),
    # userprofile
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    # comment
    path('comment/', include('comment.urls', namespace='comment')),
    # djang-notifications
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # notice
    path('notice/', include('notice.urls', namespace='notice')),
    # # django-allauth
    path('accounts/', include('allauth.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [

    path('login/', views.user_login, name='login'),

    path('logout/', views.user_logout, name='logout'),

    path('register/', views.user_register, name='register'),

    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

article/models.py
from django.db import models

from django.contrib.auth.models import User

from django.utils import timezone
from django.urls import reverse

from taggit.managers import TaggableManager


from PIL import Image

class ArticleColumn(models.Model):
    """
    ArticleColumn Model
    """
    title = models.CharField(max_length=100, blank=True)
    
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class ArticlePost(models.Model):
    """
    Article Model
    """
    author = models.ForeignKey(User, on_delete=models.CASCADE)


    avatar = models.ImageField(upload_to='article/%Y%m%d/', blank=True)

    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )

    # article tags
    tags = TaggableManager(blank=True)

    # article title   
    title = models.CharField(max_length=100)

    #article text
    body = models.TextField()

    # views
    total_views = models.PositiveIntegerField(default=0)

    # likes
    likes = models.PositiveIntegerField(default=0)

    # created time 
    created = models.DateTimeField(default=timezone.now)

    # updated time
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

    def save(self, *args, **kwargs):
        article = super(ArticlePost, self).save(*args, **kwargs)

        if self.avatar and not kwargs.get('update_fields'):
            image = Image.open(self.avatar)
            (x, y) = image.size
            new_x = 400
            new_y = int(new_x * (y / x))
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
            resized_image.save(self.avatar.path)

        return article

    def was_created_recently(self):
        diff = timezone.now() - self.created
        
        if diff.days == 0 and diff.seconds >= 0 and diff.seconds < 60:
            return True
        else:
            return False

article/forms.py
from django import forms

from .models import ArticlePost


class ArticlePostForm(forms.ModelForm):
    class Meta:

        model = ArticlePost

        fields = ('title', 'body', 'tags', 'avatar')

article/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.http import HttpResponse
from .models import ArticlePost, ArticleColumn
from .forms import ArticlePostForm
import markdown
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from comment.models import Comment

from comment.forms import CommentForm

from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView

# from my_portfolio.settings import LOGGING
# import logging

# logging.config.dictConfig(LOGGING)
# logger = logging.getLogger('django.request')


def article_list(request):

    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')

    article_list = ArticlePost.objects.all()

    if search:
        article_list = article_list.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        search = ''

    if column is not None and column.isdigit():
        article_list = article_list.filter(column=column)

    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])

    if order == 'total_views':
        article_list = article_list.order_by('-total_views')

    paginator = Paginator(article_list, 3)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    context = {
        'articles': articles,
        'order': order,
        'search': search,
        'column': column,
        'tag': tag,
    }
    return render(request, 'article/list.html', context)


def article_detail(request, id):
    # article = ArticlePost.objects.get(id=id)
    # logger.warning('Something went wrong!')
    article = get_object_or_404(ArticlePost, id=id)
    
    comments = Comment.objects.filter(article=id)

    article.total_views += 1
    article.save(update_fields=['total_views'])

    pre_article = ArticlePost.objects.filter(id__lt=article.id).order_by('-id')
    next_article = ArticlePost.objects.filter(id__gt=article.id).order_by('id')
    if pre_article.count() > 0:
        pre_article = pre_article[0]
    else:
        pre_article = None

    if next_article.count() > 0:
        next_article = next_article[0]
    else:
        next_article = None


    md = markdown.Markdown(
        extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
        ]
    )
    article.body = md.convert(article.body)

    comment_form = CommentForm()

    context = { 
        'article': article,
        'toc': md.toc,
        'comments': comments,
        'pre_article': pre_article,
        'next_article': next_article,
        'comment_form': comment_form,
    }
    return render(request, 'article/detail.html', context)


@login_required(login_url='/userprofile/login/')
def article_create(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(request.POST, request.FILES)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            new_article.save()
            article_post_form.save_m2m()
            return redirect("article:article_list")
        else:
            return HttpResponse("worry,input again!")
    else:
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context = { 'article_post_form': article_post_form, 'columns': columns }
        return render(request, 'article/create.html', context)


@login_required(login_url='/userprofile/login/')
def article_delete(request, id):
    article = ArticlePost.objects.get(id=id)
    if request.user != article.author:
        return HttpResponse("sorry,you can't delete this article")
    article.delete()
    return redirect("article:article_list")


@login_required(login_url='/userprofile/login/')
def article_safe_delete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        if request.user != article.author:
            return HttpResponse("sorry,you can't delete this article")
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("post request only")


@login_required(login_url='/userprofile/login/')
def article_update(request, id):

    article = ArticlePost.objects.get(id=id)

    if request.user != article.author:
        return HttpResponse("sorry,you can't delete this article!")

    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            article.title = request.POST['title']
            article.body = request.POST['body']

            if request.POST['column'] != 'none':
                article.column = ArticleColumn.objects.get(id=request.POST['column'])
            else:
                article.column = None

            if request.FILES.get('avatar'):
                article.avatar = request.FILES.get('avatar')

            article.tags.set(*request.POST.get('tags').split(','), clear=True)
            article.save()
            return redirect("article:article_detail", id=id)
        else:
            return HttpResponse("context error,input again!")

    else:
        article_post_form = ArticlePostForm()

        columns = ArticleColumn.objects.all()
        context = { 
            'article': article, 
            'article_post_form': article_post_form,
            'columns': columns,
            'tags': ','.join([x for x in article.tags.names()]),
        }

        return render(request, 'article/update.html', context)


class IncreaseLikesView(View):
    def post(self, request, *args, **kwargs):
        article = ArticlePost.objects.get(id=kwargs.get('id'))
        article.likes += 1
        article.save()
        return HttpResponse('success')


def article_list_example(request):
    if request.method == 'GET':
        articles = ArticlePost.objects.all()
        context = {'articles': articles}
        return render(request, 'article/list.html', context)



class ContextMixin:
    """
    Mixin
    """
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        context['order'] = 'total_views'
        return context


class ArticleListView(ContextMixin, ListView):

    context_object_name = 'articles'

    template_name = 'article/list.html'

    def get_queryset(self):
        queryset = ArticlePost.objects.filter(title='Python')
        return queryset


class ArticleDetailView(DetailView):
    queryset = ArticlePost.objects.all()
    context_object_name = 'article'
    template_name = 'article/detail.html'

    def get_object(self):

        obj = super(ArticleDetailView, self).get_object()
        obj.total_views += 1
        obj.save(update_fields=['total_views'])
        return obj


class ArticleCreateView(CreateView):

    model = ArticlePost
    fields = '__all__'
    template_name = 'article/create_by_class_view.html'

templates/article/create.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} write article {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <label for="avatar">avatar</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>

                <div class="form-group">
                    <label for="title">acticle title</label>
                    <input type="text" 
                           class="form-control" 
                           id="title" 
                           name="title"
                    >
                </div>
                
                <div class="form-group">
                    <label for="column">column</label>
                    <select class="form-control col-3" 
                            id="column" 
                            name="column"
                    >
                            <option value="none">choose column..</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}">{{ column }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="tags">tags</label>
                    <input type="text" 
                           class="form-control col-3" 
                           id="tags" 
                           name="tags"
                    >
                </div>

                <div class="form-group">
                    <label for="body">text</label>
                    <textarea type="text" 
                              class="form-control" 
                              id="body" 
                              name="body" 
                              rows="12"
                    ></textarea>
                </div>
                <button type="submit" class="btn btn-primary">completed</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/create_by_class_view.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

templates/article/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Article
{% endblock title %}

{% block content %}
<script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'prism/prism.css' %}">

<div class="container">
    <div class="row">
        <div class="col-9">
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success">
                <div>
                    Author:{{ article.author }}
                    {% if user == article.author %}

                        · <a href="#" onclick="confirm_safe_delete()">delete article</a>
                        <form 
                            style="display:none;" 
                            id="safe_delete"
                            action="{% url 'article:article_safe_delete' article.id %}" 
                            method="POST"
                        >
                        {% csrf_token %}
                            <button type="submit">send</button>
                        </form>

                        · <a href="{% url "article:article_update" article.id %}">
                            edit article
                        </a>
                    {% endif %}
                </div>
                <div>
                    view:{{ article.total_views }}
                </div>
            </div>
            <div class="col-12">
                <p>{{ article.body|safe }}</p>
            </div>

            <div style="text-align:center;" class="mt-4">
                <button class="btn btn-outline-danger"
                        type="button"
                        onclick="validate_is_like(
                                '{% url 'article:increase_likes' article.id %}',
                                {{ article.id }},
                                {{ article.likes }}
                            )"
                >
                    <span>likes</span>
                    <span>
                        <i class="fas fa-heart"></i>
                    </span>
                    <span id="likes_number">
                        {{ article.likes }}
                    </span>
                </button>
            </div>

            <br>
            <div class="row justify-content-end">
                {% if next_article %}
                <div class="col-auto mr-auto">
                    <a  href="{{ next_article.get_absolute_url }}" 
                        class="btn btn-info"
                        >
                        {{ next_article.title }}
                    </a>
                </div>
                {% endif %}
            {% if pre_article %}
                <div class="col-auto">
                    <a  href="{{ pre_article.get_absolute_url }}" 
                    class="btn btn-info" 
                    >
                        {{ pre_article.title }}
                    </a>
                </div>
            {% endif %}
            </div>


            <hr>
            {% if user.is_authenticated %}
                <div>
                    <form 
                        action="{% url 'comment:post_comment' article.id %}" 
                        method="POST"
                    >
                    {% csrf_token %}
                        <div class="form-group">
                            <label for="body">
                                <strong>
                                    I want to say:
                                </strong>
                            </label>
                            <div>
                                {{ comment_form.media }}
                                {{ comment_form.body }}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary ">send</button>
                    </form>
                </div>
                <br>
            {% else %}
                <br>
                <h5 class="row justify-content-center">
                    please <a href="{% url 'userprofile:login' %}"> login </a>to reply
                </h5>
                <br>
            {% endif %}
            


            {% load mptt_tags %}
            <h4>{{ comments.count }} comments</h4>
            <div class="row">
                {% recursetree comments %}
                    {% with comment=node %}
                        <div class="{% if comment.reply_to %}
                                    offset-1 col-11
                                    {% else %}
                                    col-12
                                    {% endif %}"
                            id="comment_elem_{{ comment.id }}" 
                        >
                            <hr>
                            <p>
                                <strong style="color: pink">
                                    {{ comment.user }}
                                </strong> 

                                {% if comment.reply_to %}
                                    <i class="far fa-arrow-alt-circle-right" 
                                       style="color: cornflowerblue;"
                                    ></i>
                                    <strong style="color: pink">
                                        {{ comment.reply_to }}
                                    </strong> 
                                {% endif %}

                            </p>
                            <div>{{ comment.body|safe }}</div>

                            <div>
                                <span style="color: gray">
                                    {{ comment.created|date:"Y-m-d H:i" }}
                                </span>

                                {% if user.is_authenticated %}
                                    <button type="button" 
                                            class="btn btn-light btn-sm text-muted" 
                                            onclick="load_modal({{ article.id }}, {{ comment.id }})"
                                    >
                                        reply
                                    </button>
                                {% else %}
                                    <a class="btn btn-light btn-sm text-muted" 
                                        href="{% url 'userprofile:login' %}"
                                    >
                                        reply
                                    </a>
                                {% endif %}
                            </div>

                            <!-- Modal -->
                            <div class="modal fade" 
                                 id="comment_{{ comment.id }}" 
                                 tabindex="-1" 
                                 role="dialog" 
                                 aria-labelledby="CommentModalCenter" 
                                 aria-hidden="true"
                            >
                                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                    <div class="modal-content" style="height: 480px">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">reply {{ comment.user }}：</h5>
                                        </div>
                                        <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                    </div>
                                </div>
                            </div>

                            {% if not comment.is_leaf_node %}
                                <div class="children">
                                    {{ children }}
                                </div>
                            {% endif %}
                        </div>
                        
                    {% endwith %}
                {% endrecursetree %}
            </div>  
        </div>

        <div class="col-3 mt-4" id="sidebar" class="sidebar">
            <div class="sidebar__inner">
                <h4><strong>list</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .sidebar{
        will-change: min-height;
    }

    .sidebar__inner{
        transform: translate(0, 0); /* For browsers don't support translate3d. */
        transform: translate3d(0, 0, 0);
        will-change: position, transform;
    }
</style>

<script>
    function confirm_delete() {
        layer.open({
            title: "Delete?",
            content: "Delete?",
            yes: function(index, layero) {
                location.href='{% url "article:article_delete" article.id %}'
            },
        })
    }

    function confirm_safe_delete() {
        layer.open({
            title: "Delete?",
            content: "Delete?",
            yes: function(index, layero) {
                $('form#safe_delete button').click();
                layer.close(index);
            }
        })
    }
</script>
{% endblock content %}

{% block script %}

<!-- csrf token -->
<script src="{% static 'csrf.js' %}"></script>
<script>
    function validate_is_like(url, id, likes) {
        let storage = window.localStorage;
        const storage_str_data = storage.getItem("my_blog_data");
        let storage_json_data = JSON.parse(storage_str_data);
        if (!storage_json_data) {
            storage_json_data = {}
        };
        const status = check_status(storage_json_data, id);
        if (status) {
            layer.msg('liked~');
            return;
        } else {
            $('span#likes_number').text(likes + 1).css('color', '#dc3545');
        }
        $.post(
            url,
            {},
            function(result) {
                if (result === 'success') {
                    try {
                        storage_json_data[id] = true;
                    } catch (e) {
                        window.localStorage.clear();
                    };

                    const d = JSON.stringify(storage_json_data);
                    try {
                        storage.setItem("my_blog_data", d);
                    } catch (e) {
                        if (e.code === 22) {
                            window.localStorage.clear();
                            storage.setItem("my_blog_data", d);
                        }
                    };
                } else {
                    layer.msg("connected server fail");
                }

            }
        );
    };
    function check_status(data, id) {
        try {
            if (id in data && data[id]) {
                return true;
            } else {
                return false;
            }
        } catch (e) {
            window.localStorage.clear();
            return false;
        };
    };
</script>

<script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
<script type="text/javascript">
    $('#sidebar').stickySidebar({
        topSpacing: 20,
        bottomSpacing: 20,
    });
</script>

<script>
    $(".django-ckeditor-widget").removeAttr('style');
</script>

<script>
    function load_modal(article_id, comment_id) {
        let modal_body = '#modal_body_' + comment_id;
        let modal_id = '#comment_' + comment_id;

        if ($(modal_body).children().length === 0) {
            let content = '<iframe src="/comment/post-comment/' + 
                article_id + 
                '/' + 
                comment_id + 
                '" frameborder="0" style="width: 100%; height: 100%;"></iframe>';
            $(modal_body).append(content);
        };

        $(modal_id).modal('show');
    };

    function post_reply_and_show_it(new_comment_id) {
        let next_url = "{% url 'article:article_detail' article.id %}";
        next_url = next_url.charAt(next_url.length - 1) == '/' ? next_url.slice(0, -1) : next_url;
        window.location.replace(next_url + "#comment_elem_" + new_comment_id);
    };
</script>
{% endblock script %}

templates/article/tag_list.html
<ul>
{% for comment in comments %}
    <li> {{ comment.created }} </li>
{% endfor %}
</ul>

templates/article/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} upload {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <label for="title">title</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>

                <div class="form-group">
                    <label for="column">column</label>
                    <select class="form-control" 
                            id="column" 
                            name="column"
                    >
                            <option value="none">choose column..</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}"
                                {% if column.id == article.column.id %}
                                    selected
                                {% endif %}
                            >
                                {{ column }}
                            </option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                   <label for="avatar">avatar</label>
                   <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>

                <div class="form-group">
                     <label for="tags">tags</label>
                     <input type="text" class="form-control col-3" id="tags" name="tags"
                        value="{{ tags }}">
                </div>

                <div class="form-group">
                    <label for="body">body</label>
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>

                <button type="submit" class="btn btn-primary">completed</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}